version: '3.9'

services:
  app:
    build: ./flask-app
    container_name: app
    env_file: .env
    depends_on:
      - db
    networks:
      - backend
    expose:
      - 5000

  db:
    image: postgres:15
    container_name: db
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts:/scripts
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - backend

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://user:password@db:5432/tasks_db?sslmode=disable"
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "9187:9187"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
